global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus_metrics'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'node-exporter_metrics'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'cadvisor_metrics'
    static_configs:
      - targets: ['cadvisor:8080']